### ISSUE TITLE
Unable to download using this tool

### ISSUE THREAD

**Issue by charlesxu90** [PeterTheOne/slideslive-slides-dl#19]
```python
Traceback (most recent call last):
  File "~/Downloads/Slideslive/slideslive-slides-dl/slideslive-slides-dl.py", line 122, in <module>
    create_ffmpeg_concat_file(video_id, video_name, df, args.size)
  File "~/Downloads/Slideslive/slideslive-slides-dl/slideslive-slides-dl.py", line 91, in create_ffmpeg_concat_file
    duration = int(row['timeSec']) - last_time
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by DungMinhDao** [comment]
Does anyone have a workaround?

**Comment by smsnobin77** [comment]
I tried and didn't work.

**Comment by JasonGross** [comment]
Since https://github.com/yt-dlp/yt-dlp/pull/5784, you can use `yt-dlp --write-all-thumbnails` to get slides.  Maybe the code there will also contain hints about how to solve this problem here.
